### ISSUE TITLE
the camera doesnt work and streaming black screen issue

### ISSUE THREAD

**Issue by jonfrusciante** [ramprasadm1986/cordova-rtmp-stream#1]
i i try your plugin thank for your work for the community!!!

but all seem to be ok when i try to stream i see only black screen on my server i see that the rtmp connection is incoming but with no image and audio also in the app i see only BLACK SCREEN ...

its only my problem ???

**Comment by ramprasadm1986** [comment]
@jonfrusciante are you using for iOS or Andriod?
if you are using for iOS please add the following  swift (swift 5) package in your XCODE Project
https://github.com/shogo4405/HaishinKit.swift

**Comment by 4external** [comment]
@jonfrusciante

>  i see only BLACK SCREEN ...

it's because maskView is black. remove it or change opacity.

@ramprasadm1986 what's purpose for maskView?

**Comment by ramprasadm1986** [comment]
maskView  is for hidden stream(black overlay on the screen) (click at top right, stream will stop) , i will update the plugin in next release for hidden stream as a plugin parameter for the maskView .
